pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/Arunkumar0126/JenkinsWar.git', branch: 'master'
            }
        }

        stage('maven version checking') {
            steps {
                sh '/opt/maven/bin/mvn -v'
            }
        }
        stage('Build') {
            steps {
                sh '/opt/maven/bin/mvn clean install'
            }
        }
        stage('tomcat deployment') {
            steps {
                sh 'cp -r target/JenkinsWar.war /opt/tomcat11/webapps/currentrelease/'
            }
        }
        stage('extract war file') {
            steps {
                sh 'unzip JenkinsWar.war -d junemonthrelease'
            }
        }		
    }
}
